# AWK ES UN PROGRAMA QUE NOS PERMITE REALIZAR DIFERENTES TIPOS DE OPERACIONES
# POR EJEMPLO, EXTRAEREMOS INFORMACIÓN DE LA PRIMERA COLUMNA DE UN ARCHIVO CSV
echo 'IMPRIMIMOS LOS REGISTROS DE UN ARCHIVO CSV'
cat patrones.csv | awk -F';' '{print $1}'

# EL PARÁMETRO 'F' SIRVE PARA EXPLICITAR EL CARACTER QUE DELIMITA UNA COLUMNA, COMO EN ESTE CASO ESTAMOS TRABAJANDO CON UN CSV, EL ";" ES EL RESPONSABLE

# SIN EMBARGO, EL AWK TAMBIÉN NOS PERMITE IMPRIMIR VARIAS COLUMNAS A LA VEZ
echo -e '\nIMPRIMIMOS ALGUNAS COLUMNAS DE UN ARCHIVO DIRECTAMENTE CON EL AWK'
awk -F':' '{print $1"\t"$4"\t"$7}' /etc/passwd

# SE PUEDEN CONFIGURAR TAMBIÉN DE OTRAS FORMAS
echo -e '\nIMPRIMIMOS EL MISMO ARCHIVO PERO CON DIFERENTE CONFIGURACIÓN'
awk 'BEGIN{FS=":"; OFS="-"} {print $1,$6,$7}' /etc/passwd

# ACÁ VAMOS A IMPRIMIR TODOS LOS SHELLS EXISTENTES EN NUESTRO SISTEMA
echo -e '\nIMPRIMIENDO TODOS LOS SHELLS DEL SISTEMA'
cat /etc/shells
echo 'SIN EMBARGO, NOSOTROS SOLO QUEREMOS LOS NOMBRES'
awk -F'/' '{print $NF}' /etc/shells
echo 'AUNQUE, SI VEMOS LA PRIMERA LÍNEA, HAY TEXTO QUE NO QUEREMOS'
awk -F'/' '/^\// {print $NF}' /etc/shells
echo 'A PESAR DE TODO LO QUE HICIMOS, HAY CONTENIDO REPETIDO, TOCA BORRARLO'
awk -F'/' '/^\// {print $NF}' /etc/shells | uniq

echo -e '\nVAMOS A IMPRIMIR UN REPORTE DEL USO DE ESPACIO DEL SISTEMA'
df
echo 'ELIMINAMOS LA PRIMERA FILA E IMPRIMIMOS ALGUNAS COLUMNAS (1, 2+3) Y REALIZAMOS UNA OPERACIÓN ARITMÉTICA'
df | awk '/^[^File]/ {print $1"\t" $2+$3}'
echo 'PERO TAMBIÉN QUEREMOS FILTRAR LOS RESULTADOS SEGÚN SU TAMAÑO, EN ESTE CASO, 4 CARACTERES'
df | awk 'length($1)==4 {print $1"\t" $2+$3}'
echo 'PODEMOS FILTRAR TAMBIÉN USANDO REGEX'
ps -ef | awk '{ if($NF ~ /^\/usr\/bin/) print $NF }'
echo 'USANDO NUEVAMENTE REGEX'
ps -ef | awk '{ if(match($NF, /^\/usr\//)) print $NF }'
echo 'INCLUSO PODEMOS INCLUIR LOOPS ADENTRO'
awk 'BEGIN{ for(i=1; i<=10; i++) print "La potencia al cuadrado de", i, "es", i*i;}'
echo 'PROCEDEMOS A COMERNOS EL LAS PRIMERAS 4 LETRAS DE UNA LISTA'
awk '{ print substr($0, 5)}' lista.txt
echo 'VAMOS A IMPRIMIR DESDE LA LINEA 3 A LA LINEA 7 DE LA LISTA'
awk '{ if(NR>=3 && NR<=7) print NR" "$2 }' lista.txt
echo 'FINALMENTE, CONTAMOS TODAS LS LINEAS DE LA LISTA'
awk 'END { print NR }' lista.txt

# DE HECHO, TAMBIÉN PODEMOS FILTRAR POR COLUMNAS
echo 'IMPRIMIMOS SOLO LOS RESULTADOS DE LA ÚLTIMA COLUMNA SI ESTOS EMPIEZAN CON "R"'
cat lista.txt | awk -F '. ' '$NF~/^[R]/ { print $NF }'

